[destination.filesystem]
bucket_url = "s3://farol-raw"

[destination.filesystem.credentials]
aws_access_key_id = "${MINIO_ACCESS_KEY}"
aws_secret_access_key = "${MINIO_SECRET_KEY}"
endpoint_url = "${MINIO_ENDPOINT}"
