spark.master                                 local[4]
spark.driver.memory                          1280m
spark.sql.shuffle.partitions                 8
spark.sql.session.timeZone                   UTC
spark.ui.enabled                             false
spark.sql.extensions                         org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions
spark.sql.catalog.lake                       org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.lake.catalog-impl          org.apache.iceberg.nessie.NessieCatalog
spark.sql.catalog.lake.uri                   http://nessie:19120/api/v2
spark.sql.catalog.lake.ref                   ${NESSIE_REF}
spark.sql.catalog.lake.warehouse             s3://warehouse
spark.sql.catalog.lake.io-impl               org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.lake.s3.endpoint           ${S3_ENDPOINT}
spark.sql.catalog.lake.s3.path-style-access  true
spark.sql.catalog.lake.s3.access-key-id      ${S3_ACCESS_KEY}
spark.sql.catalog.lake.s3.secret-access-key  ${S3_SECRET_KEY}
spark.sql.catalog.lake.client.region         us-east-1
spark.sql.defaultCatalog                     lake
spark.connect.grpc.binding.port              15002
spark.driver.extraJavaOptions                -Dsun.net.inetaddr.ttl=5 -Dsun.net.inetaddr.negative.ttl=1
