version: 2

models:
  - name: dim_politico
    columns:
      - name: politico_sk
        tests: [not_null]
      - name: cpf
        tests: [not_null, unique]
      - name: nome_civil
      - name: nome_eleitoral
      - name: sigla_partido
      - name: sigla_uf
      - name: source_url
        tests: [not_null]
      - name: extracted_at
        tests: [not_null]
      - name: source_version
        tests: [not_null]

  - name: politico_id_externo
    columns:
      - name: politico_id_externo_sk
        tests: [unique, not_null]
      - name: cpf
        tests: [not_null]
      - name: fonte
        tests:
          - not_null
          - accepted_values:
              values: ['camara', 'senado', 'tse']
      - name: id_externo
        tests: [not_null]
      - name: valid_from
      - name: valid_to
      - name: is_current
      - name: source_url
        tests: [not_null]
      - name: extracted_at
        tests: [not_null]
      - name: source_version
        tests: [not_null]
