name: 'farol'
version: '1.0.0'
config-version: 2

profile: 'farol'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  farol:
    bronze:
      +materialized: table
    silver:
      +materialized: table
    gold: {}
